apiVersion: batch/v1
kind: Job
metadata:
 name: spark-hive
spec:
 template:
   spec:
     serviceAccountName: spark
     containers:
     - name: spark-hive
       image: registry.njuics.cn/wdongyu/spark:2.4.0
       command: ["/opt/spark/bin/spark-submit", "--master", "k8s://https://172.16.1.137:6443", "--deploy-mode", "cluster", "--name", "spark-hive", "--class", "com.wdongyu.hive.SparkHive", "--conf", "spark.executor.instances=5", "--conf", "spark.kubernetes.container.image.pullPolicy=Always", "--conf", "spark.kubernetes.container.image=registry.njuics.cn/wdongyu/spark:2.4.0", "--conf", "spark.kubernetes.namespace=kerong", "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark", "--conf", "spark.kubernetes.driver.volumes.persistentVolumeClaim.share-jars.mount.path=/jars", "--conf", "spark.kubernetes.driver.volumes.persistentVolumeClaim.share-jars.options.claimName=share-jars", "--conf", "spark.kubernetes.driver.label.job-pod=SparkHive", "local:///jars/SparkHive-1.0-SNAPSHOT.jar"]
     restartPolicy: Never